; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AI File Organizer"
#define MyAppVersion "1.7"
#define MyAppPublisher "Remsey Mailjard"
#define MyAppURL "https://www.remsey.nl"
#define MyAppExeName "AI-FileOrganizer.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{610BFAB5-7964-46FD-AC44-FD3E8367A004}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\Installer\MIT License (MIT-licentie).txt
InfoBeforeFile=C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\Installer\installatie-informatie.txt
InfoAfterFile=C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\Installer\na-installatie-informatie.txt
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\Installer
OutputBaseFilename=AIFileOrganizerInstall
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "dutch"; MessagesFile: "compiler:Languages\Dutch.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\AI-FileOrganizer.application"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\AI-FileOrganizer.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\AI-FileOrganizer.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\AI-FileOrganizer.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.AI.OpenAI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.AI.OpenAI.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.AI.Vision.ImageAnalysis.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.AI.Vision.ImageAnalysis.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Azure.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\CredentialManagement.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\DocumentFormat.OpenXml.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\DocumentFormat.OpenXml.Framework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\DocumentFormat.OpenXml.Framework.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\DocumentFormat.OpenXml.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\GenerativeAI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\GenerativeAI.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Google.Protobuf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Google.Protobuf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Google.Protobuf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.AsyncInterfaces.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.HashCode.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.HashCode.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Bcl.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.DependencyInjection.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.DependencyInjection.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Logging.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Logging.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Options.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.Extensions.Primitives.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.ML.OnnxRuntime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.ML.OnnxRuntime.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.ML.Tokenizers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.ML.Tokenizers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.WindowsAPICodePack.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.WindowsAPICodePack.Shell.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.WindowsAPICodePack.Shell.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Microsoft.WindowsAPICodePack.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\onnxruntime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\OpenAI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\OpenAI.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.ClientModel.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.ClientModel.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Collections.Immutable.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Collections.Immutable.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.ComponentModel.Annotations.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Diagnostics.DiagnosticSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Diagnostics.DiagnosticSource.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.IO.Pipelines.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.IO.Pipelines.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Memory.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Memory.Data.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Text.Encodings.Web.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Text.Encodings.Web.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Text.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Text.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.Threading.Tasks.Extensions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.ValueTuple.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\System.ValueTuple.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Core.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.DocumentLayoutAnalysis.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.DocumentLayoutAnalysis.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.DocumentLayoutAnalysis.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Fonts.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Fonts.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Fonts.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Package.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Package.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Package.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokenization.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokenization.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokenization.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokens.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokens.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.Tokens.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\UglyToad.PdfPig.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Document.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Document.NET.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Drawing.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Drawing.NET.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Pdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Words.NET.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Remse\Desktop\Mijn portfolio\Applicaties\AI-FileOrganizer\bin\Release\Xceed.Words.NET.xml"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

